### ISSUE TITLE
Includes front-end JavaScript libraries with known security vulnerabilities

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/GoMikeDesigns#7]
## Before
_<sub>Note: Info provided is prior to action taken to increase **SEO**._ </sub>

**Issue**: Includes front-end JavaScript libraries with known security vulnerabilities
**Category**: _Best Practices_
**Explanation**: Some third-party scripts may contain known security vulnerabilities that are easily identified and exploited by attackers
**Code Sample**: _below are the third-party JavaScript libraries that contain security vulnerabilites_
Bootstrap@3.3.5 
jQuery@2.1.0

**Comment by mwhite192** [comment]
## After
_<sub>Note: Info provided occurs after action is taken to increase **SEO**._ </sub>

**Action Taken:** Upgraded/Updated both JavaScript and Bootstrap libriaries to latest version
**Code  Sample:**
https://github.com/mwhite192/GoMikeDesigns/blob/6b67d7ce0c948384390cb631d44befe43e104d1e/index.html#L16-L17
https://github.com/mwhite192/GoMikeDesigns/blob/6b67d7ce0c948384390cb631d44befe43e104d1e/page2.html#L16-L17

**Comment by AccessiT3ch** [comment]
@mwhite192 - this one will be a little tricky, basically there are known vulnerabilities in the old version of jquery that's being used. The quick fix is to simply update the library to a newer version, but there's a bit of a catch that will only allow you to upgrade so far. In this case we can only upgrade to the latest `1.x.x` version of the script because the site's scripts are using jquery functions that are deprecated and dropped in versions `2.0.0` and higher.
